DARK_SKY_API_KEY = ""
NEWS_API_KEY = ""
MAILGUN_API_KEY = ""
NOMINATIM_USER_AGENT = ""

# MAIL
MAILGUN_DOMAIN = ""
MAILGUN_FROM_ADDR = ""

TITLE_EXCLUSIONS = ["video:", "watch:"]
MIN_PARAGRAPHS_FOR_AN_ARTICLE = 5